Repository NVIDIA-NeMo/Megatron-Bridge, pull requests merged in 2025-08, with the labels that each got.

#376 Add unit tests for fault tolerance integration
  tests/unit_tests/training/test_fault_tolerance.py
Labels: testing

#347 chore: Release branch readiness
  CHANGELOG.md
  src/megatron/bridge/package_info.py
Labels: r0.1.0

#329 Add tests for fusions checks
  tests/unit_tests/utils/test_fusions.py
Labels: testing

#350 Deepseek recipes + deepseek providers
  src/megatron/bridge/models/deepseek/__init__.py
  src/megatron/bridge/models/deepseek/deepseek_provider.py
  src/megatron/bridge/recipes/deepseek/__init__.py
  src/megatron/bridge/recipes/deepseek/deepseek_v2.py
  src/megatron/bridge/recipes/deepseek/deepseek_v2_lite.py
  src/megatron/bridge/recipes/deepseek/deepseek_v3.py
Labels: r0.1.0

#435 Cherry pick `Deepseek recipes + deepseek providers (350)` into `r0.1.0`
  src/megatron/bridge/models/deepseek/__init__.py
  src/megatron/bridge/models/deepseek/deepseek_provider.py
  src/megatron/bridge/recipes/deepseek/__init__.py
  src/megatron/bridge/recipes/deepseek/deepseek_v2.py
  src/megatron/bridge/recipes/deepseek/deepseek_v2_lite.py
  src/megatron/bridge/recipes/deepseek/deepseek_v3.py
Labels: Run CICD, cherry-pick

#438 Cherry pick `build: Upgrade TE to 2.7 (431)` into `r0.1.0`
  .github/workflows/install-test.yml
  docker/Dockerfile.ci
  docker/common/install.sh
  pyproject.toml
  uv.lock
Labels: Run CICD, cherry-pick

#441 Cherry pick `fix: Update llama 3.18b default model sequence length (413)` into `r0.1.0`
  src/megatron/bridge/recipes/llama/llama31_8b.py
  tests/unit_tests/recipes/llama/test_llama31_8b.py
Labels: Run CICD, cherry-pick

#452 [sync] Add option for sharp enabled group
  src/megatron/bridge/training/config.py
  src/megatron/bridge/training/initialize.py
Labels: r0.1.0

#450 [sync] mxfp8 reuse grad buf for param all gather sync
  src/megatron/bridge/training/mixed_precision.py
  src/megatron/bridge/training/train.py
  tests/unit_tests/training/test_mixed_precision.py
  tests/unit_tests/training/test_train.py
Labels: r0.1.0

#458 Cherry pick `[sync] mxfp8 reuse grad buf for param all gather sync (450)` into `r0.1.0`
  src/megatron/bridge/training/mixed_precision.py
  src/megatron/bridge/training/train.py
  tests/unit_tests/training/test_mixed_precision.py
  tests/unit_tests/training/test_train.py
Labels: Run CICD, cherry-pick

#456 fix: explicitly configure qwen3 moe recipes to set ETP=1
  src/megatron/bridge/recipes/qwen/qwen3_235b_a22b.py
  src/megatron/bridge/recipes/qwen/qwen3_30b_a3b.py
Labels: r0.1.0

#447 Refactor inference model load
  src/megatron/bridge/training/mlm_compat/model.py
  src/megatron/bridge/training/model_load_save.py
  tests/functional_tests/training/test_load_model.py
  tests/unit_tests/training/mlm_compat/test_get_model.py
  tests/unit_tests/training/mlm_compat/test_model.py
  tests/unit_tests/training/test_model_load_save.py
Labels: r0.1.0

#461 Cherry pick `fix: explicitly configure qwen3 moe recipes to set ETP=1 (456)` into `r0.1.0`
  src/megatron/bridge/recipes/qwen/qwen3_235b_a22b.py
  src/megatron/bridge/recipes/qwen/qwen3_30b_a3b.py
Labels: Run CICD, cherry-pick

#370 Add end to end test script for CI
  tests/end_to_end_tests/__init__.py
  tests/end_to_end_tests/train_from_recipe.py
Labels: testing, r0.1.0

#463 Cherry pick `fix: multi-gpu distributed fallback for model provider (454)` into `r0.1.0`
  examples/models/list_supported_bridges.py
  src/megatron/bridge/models/model_provider.py
Labels: Run CICD, cherry-pick

#464 Cherry pick `Add end to end test script for CI (370)` into `r0.1.0`
  tests/end_to_end_tests/__init__.py
  tests/end_to_end_tests/train_from_recipe.py
Labels: Run CICD, cherry-pick

#468 fix: Use `track_moe_metrics` from mcore
  src/megatron/bridge/training/utils/train_utils.py
  tests/unit_tests/training/utils/test_train_utils.py
Labels: r0.1.0

#469 fix: re-computed mlm padded vocab size for load
  src/megatron/bridge/training/model_load_save.py
  tests/functional_tests/training/test_load_model.py
  tests/unit_tests/training/test_model_load_save.py
Labels: r0.1.0

#489 default to using 8 workers for dataloading
  src/megatron/bridge/recipes/deepseek/deepseek_v2.py
  src/megatron/bridge/recipes/deepseek/deepseek_v2_lite.py
  src/megatron/bridge/recipes/deepseek/deepseek_v3.py
  src/megatron/bridge/recipes/gpt/gpt3_175b.py
  src/megatron/bridge/recipes/llama/llama2_7b.py
  src/megatron/bridge/recipes/llama/llama31_405b.py
  src/megatron/bridge/recipes/llama/llama31_70b.py
  src/megatron/bridge/recipes/llama/llama31_8b.py
  src/megatron/bridge/recipes/llama/llama32_1b.py
  src/megatron/bridge/recipes/llama/llama32_3b.py
  src/megatron/bridge/recipes/llama/llama3_70b.py
  src/megatron/bridge/recipes/llama/llama3_8b.py
  src/megatron/bridge/recipes/llama/llama4_e128.py
  src/megatron/bridge/recipes/llama/llama4_e16.py
  src/megatron/bridge/recipes/mamba/mamba2_130m.py
  src/megatron/bridge/recipes/mamba/mamba2_1_3b.py
  src/megatron/bridge/recipes/mamba/mamba2_2_7b.py
  src/megatron/bridge/recipes/mamba/mamba2_370m.py
  src/megatron/bridge/recipes/mamba/mamba2_780m.py
  src/megatron/bridge/recipes/mamba/mamba2_8b.py
  src/megatron/bridge/recipes/mamba/mamba2_hybrid_8b.py
  src/megatron/bridge/recipes/mamba/nemotron_nano_12b_v2.py
  src/megatron/bridge/recipes/mamba/nemotron_nano_9b_v2.py
  src/megatron/bridge/recipes/mamba/nemotronh_47b.py
  src/megatron/bridge/recipes/mamba/nemotronh_4b.py
  src/megatron/bridge/recipes/mamba/nemotronh_56b.py
  src/megatron/bridge/recipes/mamba/nemotronh_8b.py
  tests/unit_tests/recipes/gpt/test_gpt3_175b.py
  tests/unit_tests/recipes/llama/test_llama2_7b.py
  tests/unit_tests/recipes/llama/test_llama31_405b.py
  tests/unit_tests/recipes/llama/test_llama31_70b.py
  tests/unit_tests/recipes/llama/test_llama31_8b.py
  tests/unit_tests/recipes/llama/test_llama32_1b.py
  tests/unit_tests/recipes/llama/test_llama32_3b.py
  tests/unit_tests/recipes/llama/test_llama3_70b.py
  tests/unit_tests/recipes/llama/test_llama3_70b_16k.py
  tests/unit_tests/recipes/llama/test_llama3_70b_64k.py
  tests/unit_tests/recipes/llama/test_llama3_8b.py
  tests/unit_tests/recipes/llama/test_llama3_8b_16k.py
  tests/unit_tests/recipes/mamba/test_mamba2_130m.py
  tests/unit_tests/recipes/mamba/test_mamba2_1_3b.py
  tests/unit_tests/recipes/mamba/test_mamba2_2_7b.py
  tests/unit_tests/recipes/mamba/test_mamba2_370m.py
  tests/unit_tests/recipes/mamba/test_mamba2_780m.py
  tests/unit_tests/recipes/mamba/test_mamba2_8b.py
  tests/unit_tests/recipes/mamba/test_mamba2_hybrid_8b.py
  tests/unit_tests/recipes/mamba/test_nemotron_nano_12b_v2.py
  tests/unit_tests/recipes/mamba/test_nemotron_nano_9b_v2.py
  tests/unit_tests/recipes/mamba/test_nemotronh_47b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_4b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_56b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_8b.py
Labels: r0.1.0

#490 Cherry pick `default to using 8 workers for dataloading (489)` into `r0.1.0`
  src/megatron/bridge/recipes/deepseek/deepseek_v2.py
  src/megatron/bridge/recipes/deepseek/deepseek_v2_lite.py
  src/megatron/bridge/recipes/deepseek/deepseek_v3.py
  src/megatron/bridge/recipes/gpt/gpt3_175b.py
  src/megatron/bridge/recipes/llama/llama2_7b.py
  src/megatron/bridge/recipes/llama/llama31_405b.py
  src/megatron/bridge/recipes/llama/llama31_70b.py
  src/megatron/bridge/recipes/llama/llama31_8b.py
  src/megatron/bridge/recipes/llama/llama32_1b.py
  src/megatron/bridge/recipes/llama/llama32_3b.py
  src/megatron/bridge/recipes/llama/llama3_70b.py
  src/megatron/bridge/recipes/llama/llama3_8b.py
  src/megatron/bridge/recipes/llama/llama4_e128.py
  src/megatron/bridge/recipes/llama/llama4_e16.py
  src/megatron/bridge/recipes/mamba/mamba2_130m.py
  src/megatron/bridge/recipes/mamba/mamba2_1_3b.py
  src/megatron/bridge/recipes/mamba/mamba2_2_7b.py
  src/megatron/bridge/recipes/mamba/mamba2_370m.py
  src/megatron/bridge/recipes/mamba/mamba2_780m.py
  src/megatron/bridge/recipes/mamba/mamba2_8b.py
  src/megatron/bridge/recipes/mamba/mamba2_hybrid_8b.py
  src/megatron/bridge/recipes/mamba/nemotron_nano_12b_v2.py
  src/megatron/bridge/recipes/mamba/nemotron_nano_9b_v2.py
  src/megatron/bridge/recipes/mamba/nemotronh_47b.py
  src/megatron/bridge/recipes/mamba/nemotronh_4b.py
  src/megatron/bridge/recipes/mamba/nemotronh_56b.py
  src/megatron/bridge/recipes/mamba/nemotronh_8b.py
  tests/unit_tests/recipes/gpt/test_gpt3_175b.py
  tests/unit_tests/recipes/llama/test_llama2_7b.py
  tests/unit_tests/recipes/llama/test_llama31_405b.py
  tests/unit_tests/recipes/llama/test_llama31_70b.py
  tests/unit_tests/recipes/llama/test_llama31_8b.py
  tests/unit_tests/recipes/llama/test_llama32_1b.py
  tests/unit_tests/recipes/llama/test_llama32_3b.py
  tests/unit_tests/recipes/llama/test_llama3_70b.py
  tests/unit_tests/recipes/llama/test_llama3_70b_16k.py
  tests/unit_tests/recipes/llama/test_llama3_70b_64k.py
  tests/unit_tests/recipes/llama/test_llama3_8b.py
  tests/unit_tests/recipes/llama/test_llama3_8b_16k.py
  tests/unit_tests/recipes/mamba/test_mamba2_130m.py
  tests/unit_tests/recipes/mamba/test_mamba2_1_3b.py
  tests/unit_tests/recipes/mamba/test_mamba2_2_7b.py
  tests/unit_tests/recipes/mamba/test_mamba2_370m.py
  tests/unit_tests/recipes/mamba/test_mamba2_780m.py
  tests/unit_tests/recipes/mamba/test_mamba2_8b.py
  tests/unit_tests/recipes/mamba/test_mamba2_hybrid_8b.py
  tests/unit_tests/recipes/mamba/test_nemotron_nano_12b_v2.py
  tests/unit_tests/recipes/mamba/test_nemotron_nano_9b_v2.py
  tests/unit_tests/recipes/mamba/test_nemotronh_47b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_4b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_56b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_8b.py
Labels: Run CICD, cherry-pick

#491 [data] switch pretrain from broadcast to replicated load
  src/megatron/bridge/data/utils.py
  src/megatron/bridge/training/gpt_step.py
Labels: r0.1.0

#486 [sync] Fix loss mask for chat datasets
  src/megatron/bridge/data/datasets/packing_utils.py
  tests/unit_tests/data/datasets/test_packing_utils.py
Labels: r0.1.0

#498 Update readme badges
  README.md
Labels: documentation

#497 1F1B EP A2A overlap integration
  src/megatron/bridge/training/comm_overlap.py
  src/megatron/bridge/training/gpt_step.py
  src/megatron/bridge/training/utils/train_utils.py
  tests/functional_tests/training/test_nvrx_straggler.py
  tests/unit_tests/training/test_comm_overlap.py
Labels: Run CICD
