Repository NVIDIA-NeMo/Megatron-Bridge, pull requests merged in 2025-09, with the labels that each got.

#532 [MCore-sync] Change TE version to 2.8 when enabling --overlap-grad-reduce and --delay-wgrad-compute at the same time
  src/megatron/bridge/training/comm_overlap.py
Labels: r0.1.0

#519 Skip attention_mask when dataset.get_attention_mask_from_fusion is set
  src/megatron/bridge/training/config.py
  src/megatron/bridge/training/gpt_step.py
Labels: Run CICD

#537 Explicitly pass `expert_tensor_parallel_size` to `initialize_model_parallel`
  src/megatron/bridge/models/model_provider.py
Labels: r0.1.0, community-request

#543 Update `check_for_nan_in_loss` and `skip_getting_attention_mask_from_dataset` setting
  scripts/performance/llm/configs/deepseek_v3_pretrain_overrides.yaml
  scripts/performance/llm/configs/llama31_405b_pretrain_overrides.yaml
  scripts/performance/llm/configs/llama3_70b_pretrain_overrides.yaml
  scripts/performance/llm/configs/llama3_8b_pretrain_overrides.yaml
  src/megatron/bridge/recipes/deepseek/deepseek_v2.py
  src/megatron/bridge/recipes/deepseek/deepseek_v2_lite.py
  src/megatron/bridge/recipes/deepseek/deepseek_v3.py
  src/megatron/bridge/recipes/gpt/gpt3_175b.py
  src/megatron/bridge/recipes/llama/llama2_7b.py
  src/megatron/bridge/recipes/llama/llama31_405b.py
  src/megatron/bridge/recipes/llama/llama31_70b.py
  src/megatron/bridge/recipes/llama/llama31_8b.py
  src/megatron/bridge/recipes/llama/llama32_1b.py
  src/megatron/bridge/recipes/llama/llama32_3b.py
  src/megatron/bridge/recipes/llama/llama3_70b.py
  src/megatron/bridge/recipes/llama/llama3_8b.py
  src/megatron/bridge/recipes/llama/llama4_e128.py
  src/megatron/bridge/recipes/llama/llama4_e16.py
  src/megatron/bridge/recipes/mamba/mamba2_130m.py
  src/megatron/bridge/recipes/mamba/mamba2_1_3b.py
  src/megatron/bridge/recipes/mamba/mamba2_2_7b.py
  src/megatron/bridge/recipes/mamba/mamba2_370m.py
  src/megatron/bridge/recipes/mamba/mamba2_780m.py
  src/megatron/bridge/recipes/mamba/mamba2_8b.py
  src/megatron/bridge/recipes/mamba/mamba2_hybrid_8b.py
  src/megatron/bridge/recipes/mamba/nemotron_nano_12b_v2.py
  src/megatron/bridge/recipes/mamba/nemotron_nano_9b_v2.py
  src/megatron/bridge/recipes/mamba/nemotronh_47b.py
  src/megatron/bridge/recipes/mamba/nemotronh_4b.py
  src/megatron/bridge/recipes/mamba/nemotronh_56b.py
  src/megatron/bridge/recipes/mamba/nemotronh_8b.py
  src/megatron/bridge/recipes/qwen/qwen25_14b.py
  src/megatron/bridge/recipes/qwen/qwen25_1p5b.py
  src/megatron/bridge/recipes/qwen/qwen25_32b.py
  src/megatron/bridge/recipes/qwen/qwen25_500m.py
  src/megatron/bridge/recipes/qwen/qwen25_72b.py
  src/megatron/bridge/recipes/qwen/qwen25_7b.py
  src/megatron/bridge/recipes/qwen/qwen2_1p5b.py
  src/megatron/bridge/recipes/qwen/qwen2_500m.py
  src/megatron/bridge/recipes/qwen/qwen2_72b.py
  src/megatron/bridge/recipes/qwen/qwen2_7b.py
  src/megatron/bridge/recipes/qwen/qwen3_14b.py
  src/megatron/bridge/recipes/qwen/qwen3_1p7b.py
  src/megatron/bridge/recipes/qwen/qwen3_235b_a22b.py
  src/megatron/bridge/recipes/qwen/qwen3_30b_a3b.py
  src/megatron/bridge/recipes/qwen/qwen3_32b.py
  src/megatron/bridge/recipes/qwen/qwen3_4b.py
  src/megatron/bridge/recipes/qwen/qwen3_600m.py
  src/megatron/bridge/recipes/qwen/qwen3_8b.py
Labels: r0.1.0, Run CICD

#575 use tensorwise fp8 scaling by default and upate name change
  scripts/performance/utils/helpers.py
  src/megatron/bridge/training/mixed_precision.py
  tests/unit_tests/recipes/llama/test_llama2_7b.py
  tests/unit_tests/recipes/llama/test_llama31_405b.py
  tests/unit_tests/recipes/llama/test_llama31_70b.py
  tests/unit_tests/recipes/llama/test_llama31_8b.py
  tests/unit_tests/recipes/llama/test_llama32_1b.py
  tests/unit_tests/recipes/llama/test_llama32_3b.py
  tests/unit_tests/recipes/llama/test_llama3_70b.py
  tests/unit_tests/recipes/llama/test_llama3_70b_16k.py
  tests/unit_tests/recipes/llama/test_llama3_70b_64k.py
  tests/unit_tests/recipes/llama/test_llama3_8b.py
  tests/unit_tests/recipes/llama/test_llama3_8b_128k.py
  tests/unit_tests/recipes/llama/test_llama3_8b_16k.py
  tests/unit_tests/recipes/llama/test_llama3_8b_64k.py
  tests/unit_tests/recipes/llama/test_llama4_e128.py
  tests/unit_tests/recipes/llama/test_llama4_e16.py
  tests/unit_tests/training/test_mixed_precision.py
Labels: r0.1.0

#584 remove config val print in perf script
  scripts/performance/run_script.py
Labels: r0.1.0, performance

#591 Add global barrier after checkpoint save to ensure synchronization across ranks
  src/megatron/bridge/training/checkpointing.py
Labels: r0.1.0

#598 Cherry pick `Add global barrier after checkpoint save to ensure synchronization across ranks (591)` into `r0.1.0`
  src/megatron/bridge/training/checkpointing.py
Labels: Run CICD, cherry-pick

#586 Cherry pick `use tensorwise fp8 scaling by default and upate name change (575)` into `r0.1.0`
  scripts/performance/utils/helpers.py
  src/megatron/bridge/training/mixed_precision.py
  tests/unit_tests/recipes/llama/test_llama2_7b.py
  tests/unit_tests/recipes/llama/test_llama31_405b.py
  tests/unit_tests/recipes/llama/test_llama31_70b.py
  tests/unit_tests/recipes/llama/test_llama31_8b.py
  tests/unit_tests/recipes/llama/test_llama32_1b.py
  tests/unit_tests/recipes/llama/test_llama32_3b.py
  tests/unit_tests/recipes/llama/test_llama3_70b.py
  tests/unit_tests/recipes/llama/test_llama3_70b_16k.py
  tests/unit_tests/recipes/llama/test_llama3_70b_64k.py
  tests/unit_tests/recipes/llama/test_llama3_8b.py
  tests/unit_tests/recipes/llama/test_llama3_8b_128k.py
  tests/unit_tests/recipes/llama/test_llama3_8b_16k.py
  tests/unit_tests/recipes/llama/test_llama3_8b_64k.py
  tests/unit_tests/recipes/llama/test_llama4_e128.py
  tests/unit_tests/recipes/llama/test_llama4_e16.py
  tests/unit_tests/training/test_mixed_precision.py
Labels: Run CICD, cherry-pick

#536 fix: reduce padded vocab size logspam
  src/megatron/bridge/training/utils/flop_utils.py
  src/megatron/bridge/training/utils/theoretical_memory_utils.py
  src/megatron/bridge/utils/vocab_utils.py
Labels: r0.1.0

#616 Cherry pick `fix: reduce padded vocab size logspam (536)` into `r0.1.0`
  src/megatron/bridge/training/utils/flop_utils.py
  src/megatron/bridge/training/utils/theoretical_memory_utils.py
  src/megatron/bridge/utils/vocab_utils.py
Labels: Run CICD, cherry-pick

#617 Cherry pick `[DSV3] Fix MTP spec issue for uneven PP and enable delay_wgrad_compute with the right version (610)` into `r0.1.0`
  src/megatron/bridge/models/gpt_provider.py
  src/megatron/bridge/training/comm_overlap.py
Labels: Run CICD, cherry-pick

#580 [docs] update contributing doc for how to run github CI
  CONTRIBUTING.md
Labels: documentation

#522 Add FP8 Tensor Support for Megatron to HuggingFace Export
  src/megatron/bridge/models/conversion/param_mapping.py
Labels: r0.1.0

#611 [megatron FSDP] Support `fsdp_dtensor` checkpoint format
  src/megatron/bridge/models/conversion/model_bridge.py
  src/megatron/bridge/models/conversion/utils.py
  src/megatron/bridge/training/checkpointing.py
  src/megatron/bridge/training/config.py
  src/megatron/bridge/training/setup.py
  src/megatron/bridge/training/train.py
  src/megatron/bridge/utils/common_utils.py
  tests/functional_tests/training/test_megatron_fsdp.py
  tests/functional_tests/training/test_pretrain.py
  tests/functional_tests/utils.py
  tests/unit_tests/training/test_checkpointing.py
  tests/unit_tests/training/test_config.py
  tests/unit_tests/training/test_train.py
  tests/unit_tests/utils/test_common_utils.py
Labels: r0.1.0

#635 Update build_train_valid_test_data_loaders to handle eval_iters=0
  src/megatron/bridge/data/loaders.py
  tests/unit_tests/data/test_loaders.py
Labels: r0.1.0

#551 Cherry pick `ci: Always run summary, check for job results (548)` into `r0.1.0`
  .github/workflows/build-docs.yml
  .github/workflows/build-test-publish-wheel.yml
  .github/workflows/cicd-main.yml
  .github/workflows/copyright-check.yml
  .github/workflows/install-test.yml
Labels: Run CICD, cherry-pick

#642 Cherry pick `Update build_train_valid_test_data_loaders to handle eval_iters=0 (635)` into `r0.1.0`
  src/megatron/bridge/data/loaders.py
  tests/unit_tests/data/test_loaders.py
Labels: Run CICD, cherry-pick

#612 add test coverage for checkpoint and decide exit
  tests/unit_tests/training/test_train.py
Labels: testing

#651 Disable bf16 layers in the default current scaling recipe
  scripts/performance/utils/helpers.py
Labels: bug, r0.1.0

#595 default bf16 grads; te loss
  src/megatron/bridge/models/llama/llama_provider.py
  src/megatron/bridge/recipes/llama/llama31_405b.py
  src/megatron/bridge/recipes/llama/llama3_70b.py
  src/megatron/bridge/recipes/llama/llama3_8b.py
  src/megatron/bridge/recipes/qwen/qwen3_235b_a22b.py
  src/megatron/bridge/recipes/qwen/qwen3_30b_a3b.py
Labels: r0.1.0, performance

#663 Fix Mamba and NemotronH recipes
  src/megatron/bridge/models/mamba/mamba_provider.py
  src/megatron/bridge/recipes/mamba/mamba2_130m.py
  src/megatron/bridge/recipes/mamba/mamba2_1_3b.py
  src/megatron/bridge/recipes/mamba/mamba2_2_7b.py
  src/megatron/bridge/recipes/mamba/mamba2_370m.py
  src/megatron/bridge/recipes/mamba/mamba2_780m.py
  src/megatron/bridge/recipes/mamba/mamba2_8b.py
  src/megatron/bridge/recipes/mamba/mamba2_hybrid_8b.py
  src/megatron/bridge/recipes/mamba/nemotron_nano_12b_v2.py
  src/megatron/bridge/recipes/mamba/nemotron_nano_9b_v2.py
  src/megatron/bridge/recipes/mamba/nemotronh_47b.py
  src/megatron/bridge/recipes/mamba/nemotronh_4b.py
  src/megatron/bridge/recipes/mamba/nemotronh_56b.py
  src/megatron/bridge/recipes/mamba/nemotronh_8b.py
  src/megatron/bridge/training/config.py
  tests/unit_tests/recipes/mamba/test_mamba2_130m.py
  tests/unit_tests/recipes/mamba/test_mamba2_1_3b.py
  tests/unit_tests/recipes/mamba/test_mamba2_2_7b.py
  tests/unit_tests/recipes/mamba/test_mamba2_370m.py
  tests/unit_tests/recipes/mamba/test_mamba2_780m.py
  tests/unit_tests/recipes/mamba/test_mamba2_8b.py
  tests/unit_tests/recipes/mamba/test_mamba2_hybrid_8b.py
  tests/unit_tests/recipes/mamba/test_nemotron_nano_12b_v2.py
  tests/unit_tests/recipes/mamba/test_nemotron_nano_9b_v2.py
  tests/unit_tests/recipes/mamba/test_nemotronh_47b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_4b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_56b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_8b.py
  tests/unit_tests/training/test_config.py
Labels: r0.1.0

#668 Cherry pick `default bf16 grads; te loss (595)` into `r0.1.0`
  src/megatron/bridge/models/llama/llama_provider.py
  src/megatron/bridge/recipes/llama/llama31_405b.py
  src/megatron/bridge/recipes/llama/llama3_70b.py
  src/megatron/bridge/recipes/llama/llama3_8b.py
  src/megatron/bridge/recipes/qwen/qwen3_235b_a22b.py
  src/megatron/bridge/recipes/qwen/qwen3_30b_a3b.py
Labels: Run CICD, cherry-pick

#672 Cherry pick `Fix Mamba and NemotronH recipes (663)` into `r0.1.0`
  src/megatron/bridge/models/mamba/mamba_provider.py
  src/megatron/bridge/recipes/mamba/mamba2_130m.py
  src/megatron/bridge/recipes/mamba/mamba2_1_3b.py
  src/megatron/bridge/recipes/mamba/mamba2_2_7b.py
  src/megatron/bridge/recipes/mamba/mamba2_370m.py
  src/megatron/bridge/recipes/mamba/mamba2_780m.py
  src/megatron/bridge/recipes/mamba/mamba2_8b.py
  src/megatron/bridge/recipes/mamba/mamba2_hybrid_8b.py
  src/megatron/bridge/recipes/mamba/nemotron_nano_12b_v2.py
  src/megatron/bridge/recipes/mamba/nemotron_nano_9b_v2.py
  src/megatron/bridge/recipes/mamba/nemotronh_47b.py
  src/megatron/bridge/recipes/mamba/nemotronh_4b.py
  src/megatron/bridge/recipes/mamba/nemotronh_56b.py
  src/megatron/bridge/recipes/mamba/nemotronh_8b.py
  src/megatron/bridge/training/config.py
  tests/unit_tests/recipes/mamba/test_mamba2_130m.py
  tests/unit_tests/recipes/mamba/test_mamba2_1_3b.py
  tests/unit_tests/recipes/mamba/test_mamba2_2_7b.py
  tests/unit_tests/recipes/mamba/test_mamba2_370m.py
  tests/unit_tests/recipes/mamba/test_mamba2_780m.py
  tests/unit_tests/recipes/mamba/test_mamba2_8b.py
  tests/unit_tests/recipes/mamba/test_mamba2_hybrid_8b.py
  tests/unit_tests/recipes/mamba/test_nemotron_nano_12b_v2.py
  tests/unit_tests/recipes/mamba/test_nemotron_nano_9b_v2.py
  tests/unit_tests/recipes/mamba/test_nemotronh_47b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_4b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_56b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_8b.py
  tests/unit_tests/training/test_config.py
Labels: Run CICD, cherry-pick

#585 [docs] Add training & customization setting for configs
  docs/index.md
  docs/training/checkpointing-config.md
  docs/training/config-container-overview.md
  docs/training/entry-points.md
  docs/training/optimizer-scheduler-config.md
  docs/training/peft-config.md
  docs/training/resiliency.md
  docs/training/training-config.md
  src/megatron/bridge/training/config.py
  src/megatron/bridge/training/fault_tolerance.py
  tests/unit_tests/training/test_nvrx_straggler.py
Labels: documentation

#567 [docs] Add docs for logging configuration
  docs/index.md
  docs/training/logging.md
Labels: documentation

#569 [docs] Add profiling docs
  docs/index.md
  docs/training/profiling.md
Labels: documentation

#656 Cherry pick `Disable bf16 layers in the default current scaling recipe (651)` into `r0.1.0`
  scripts/performance/utils/helpers.py
Labels: Run CICD, cherry-pick

#682 Support External Cuda graph
  src/megatron/bridge/training/config.py
  src/megatron/bridge/training/initialize.py
  src/megatron/bridge/training/train.py
  src/megatron/bridge/utils/common_utils.py
  tests/unit_tests/conftest.py
  tests/unit_tests/training/test_config.py
Labels: r0.1.0

#691 Link to docs in readme
  README.md
Labels: documentation

#653 save tokenizer metadata when importing checkpoint via auto bridge
  src/megatron/bridge/models/conversion/auto_bridge.py
  src/megatron/bridge/training/model_load_save.py
  tests/unit_tests/models/test_auto_bridge.py
  tests/unit_tests/training/test_model_load_save.py
Labels: r0.1.0

#703 Cherry pick `save tokenizer metadata when importing checkpoint via auto bridge (653)` into `r0.1.0`
  src/megatron/bridge/models/conversion/auto_bridge.py
  src/megatron/bridge/training/model_load_save.py
  tests/unit_tests/models/test_auto_bridge.py
  tests/unit_tests/training/test_model_load_save.py
Labels: Run CICD, cherry-pick

#706 Cherry pick `feat: in process restart integration (499)` into `r0.1.0`
  src/megatron/bridge/training/checkpointing.py
  src/megatron/bridge/training/config.py
  src/megatron/bridge/training/fault_tolerance.py
  src/megatron/bridge/training/initialize.py
  src/megatron/bridge/training/inprocess_restart.py
  src/megatron/bridge/training/pretrain.py
  src/megatron/bridge/training/setup.py
  src/megatron/bridge/training/state.py
  src/megatron/bridge/training/utils/train_utils.py
  tests/functional_tests/L2_Launch_training.sh
  tests/functional_tests/training/test_inprocess_restart.py
  tests/unit_tests/training/test_fault_tolerance.py
  tests/unit_tests/training/test_inprocess_restart.py
  tests/unit_tests/training/test_setup.py
  tests/unit_tests/training/test_state.py
  tests/unit_tests/training/utils/test_train_utils.py
Labels: Run CICD, cherry-pick

#709 Cherry pick `fix: disable comm overlap for nemotronh 47b/56b recipes (695)` into `r0.1.0`
  src/megatron/bridge/recipes/mamba/nemotronh_47b.py
  src/megatron/bridge/recipes/mamba/nemotronh_56b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_47b.py
  tests/unit_tests/recipes/mamba/test_nemotronh_56b.py
Labels: Run CICD, cherry-pick

#711 Fix small error in README
  README.md
Labels: documentation

#722 [docs] Remove `-config` suffix from docs page/url
  docs/index.md
  docs/training/checkpointing.md
  docs/training/optimizer-scheduler.md
  docs/training/peft.md
  docs/training/training-loop-settings.md
Labels: documentation

#669 Malay/dsv3 2509
  scripts/performance/argument_parser.py
  scripts/performance/configs/deepseek/deepseek_v3_llm_pretrain.yaml
  scripts/performance/run_script.py
  scripts/performance/setup_experiment.py
  scripts/performance/utils/helpers.py
Labels: r0.1.0, cherry-pick

#752 Cherry pick `Malay/dsv3 2509 (669)` into `r0.1.0`
  scripts/performance/argument_parser.py
  scripts/performance/configs/deepseek/deepseek_v3_llm_pretrain.yaml
  scripts/performance/run_script.py
  scripts/performance/setup_experiment.py
  scripts/performance/utils/helpers.py
Labels: Run CICD, cherry-pick

#718 [docs] Add mixed precision docs
  docs/index.md
  docs/training/mixed-precision.md
Labels: documentation

#809 [docs] add notes to checkpointing that save/loading path are expected to be in megatron format
  docs/training/checkpointing.md
Labels: documentation
